version: 0.2

phases:
  install:
    commands:
      - pip install codecov
  pre_build:
    commands:
      - echo prebuild
  build:
    commands:
      - coverage run tests.py
  post_build:
    commands:
      #- codecov --token=646448aa-c2cb-43f5-8214-da5d0ef8118f
      #- cat coverage.xml
      - curl -s https://codecov.io/bash
artifacts:
  files:
    - target/messageUtil-1.0.jar
  name: test-${AWS_REGION}
